### ISSUE TITLE
Setting verbose_log to yes doesn’t work

### ISSUE THREAD

**Issue by lo1tuma** [bitrise-steplib/bitrise-step-xcode-start-simulator#8]
Using the following step produces an error:

```
     - xcode-start-simulator:
         inputs:
         - destination: platform=iOS Simulator,name=iPhone 11,OS=latest
        - verbose_log: yes
```

The error message:

```
Process config: failed to parse config:
- IsVerboseLog: true: value is not in value options (opt[yes,no])
Input:
- destination: platform=iOS Simulator,name=iPhone 11,OS=latest
- verbose_log: false
- wait_for_boot_timeout: 0
- reset: false
```
